In [1]:
import numpy as np

In [2]:
one_d=np.array([range(1,11)])
one_d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [3]:
two_d=np.random.rand(3,4)
two_d

array([[0.81019523, 0.14886991, 0.10926947, 0.355602  ],
       [0.94124232, 0.22124301, 0.37358179, 0.35429663],
       [0.37252797, 0.55709182, 0.86685362, 0.85320418]])

In [4]:
three_d=np.zeros((2,3,4))

In [5]:
three_d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [6]:
a=np.array([1,2,3])

In [8]:
b=np.array([5,6,7])

In [9]:
a+b

array([ 6,  8, 10])

In [10]:
b-a

array([4, 4, 4])

In [11]:
a*b

array([ 5, 12, 21])

In [12]:
b/a

array([5.        , 3.        , 2.33333333])

In [14]:
np.mean(a)

2.0

In [15]:
np.median(b)

6.0

In [17]:
np.std(a)

0.816496580927726

In [20]:
a=np.array([range(1,13)])
reshape=a.reshape((3,4))
reshape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [22]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
print(c[0,2])

3


In [26]:
print(c[0,:])

[1 2 3]


In [27]:
print(c[:,2])

[3 6 9]


In [28]:
a=np.array([range(1,11)])
np.flip(a)

array([[10,  9,  8,  7,  6,  5,  4,  3,  2,  1]])

In [33]:
a=np.array([[1,2,3],[4,5,6]])
b=a[a<5]
b

array([1, 2, 3, 4])

In [34]:
a=np.array([[1,2,3],[4,5,6]])

In [35]:
b=a+50
b

array([[51, 52, 53],
       [54, 55, 56]])

In [36]:
b=np.array([4,5,6])
a*b

array([[ 4, 10, 18],
       [16, 25, 36]])

In [37]:
a=np.array([1,2,3])
np.dot(a,b)

32

In [38]:
a=np.array([[1,2,3],[4,5,6]])
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.matmul(a,c)

array([[30, 36, 42],
       [66, 81, 96]])

In [42]:
a=np.array([[7,9],[1,2]])
np.linalg.inv(a)

array([[ 0.4, -1.8],
       [-0.2,  1.4]])

In [43]:
np.linalg.det(a)

5.000000000000001